trigger:
  - prod

jobs:
  - job: build
    displayName: Build container
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
        displayName: 'docker login'
        env:
          DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
          DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)
      - script: docker build . -t jihartik/fmiproxy:latest
        displayName: 'build container'
      - script: docker push jihartik/fmiproxy:latest
        displayName: 'push container'
